/*
 * This source file was generated by the Gradle 'init' task
 */
package polynomialcalculator;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    @Test 
    void appHasAGreeting() {
        //App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");


    }

    @Test
    void t1() {
        //
        int rs = Calc.run("((3 + 5) * 5 + -10) * 10 / 5"); 
    }
}
