/*
 * This source file was generated by the Gradle 'init' task
 */
package polynomialcalculator;

public class App {

    public static void main(String[] args) {
        int a = Calc.run("((3 + 5) * 5 + -10) * 10 / 5");
    }
}
